---
title: "mirai - Parallel Integration"
vignette: >
  %\VignetteIndexEntry{mirai - Parallel Integration}
  %\VignetteEngine{litedown::vignette}
  %\VignetteEncoding{UTF-8}
---


### Parallel Integration

`mirai` provides an alternative communications backend for R.
This functionality was developed to fulfil a request by R Core at R Project Sprint 2023.

`make_cluster()` creates a cluster object of class 'miraiCluster', which is fully-compatible with `parallel` cluster types.
From R 4.5 onwards, mirai is recognised as one of the official cluster types and can also be created by `parallel::makeCluster(type = "MIRAI")`.

  + Specify 'n' to launch nodes on the local machine.
  + Specify 'url' for receiving connections from remote nodes.
  + Optionally, specify 'remote' to launch remote daemons using a remote configuration generated by `remote_config()` or `ssh_config()`.

Created clusters may be used for any function in the `parallel` base package such as `parallel::clusterApply()` or `parallel::parLapply()`, or the load-balanced versions such as `parallel::parLapplyLB()`.

``` r
library(mirai)

cl <- make_cluster(4)
cl
#> < miraiCluster | ID: `0` nodes: 4 active: TRUE >
parallel::parLapply(cl, iris, mean)
#> $Sepal.Length
#> [1] 5.843333
#> 
#> $Sepal.Width
#> [1] 3.057333
#> 
#> $Petal.Length
#> [1] 3.758
#> 
#> $Petal.Width
#> [1] 1.199333
#> 
#> $Species
#> [1] NA
```

`status()` may be called on a 'miraiCluster` to query the number of connected nodes at any time.

``` r
status(cl)
#> $connections
#> [1] 4
#> 
#> $daemons
#> [1] "abstract://b8163969af488f2783f411ba"
stop_cluster(cl)
```
Making a cluster specifying 'url' without 'remote' causes the shell commands for manual deployment of nodes to be printed to the console.

``` r
cl <- make_cluster(n = 2, url = host_url())
#> Shell commands for deployment on nodes:
#> 
#> [1]
#> Rscript -e 'mirai::daemon("tcp://192.168.1.71:39957",dispatcher=FALSE,cleanup=FALSE,rs=c(10407,-21525145,-661555588,1174154573,109719466,1891487011,-1198846968))'
#> 
#> [2]
#> Rscript -e 'mirai::daemon("tcp://192.168.1.71:39957",dispatcher=FALSE,cleanup=FALSE,rs=c(10407,-1817502444,932019832,-329889616,-1965248410,1885768877,1092262858))'
stop_cluster(cl)
```

### Foreach Integration

A 'miraiCluster' may also be registered by [`doParallel`](https://cran.r-project.org/package=doParallel) for use with the [`foreach`](https://cran.r-project.org/package=foreach) package.

Running some parallel examples for the `foreach()` function:


``` r
library(foreach)
library(iterators)

cl <- make_cluster(4)
doParallel::registerDoParallel(cl)

# normalize the rows of a matrix
m <- matrix(rnorm(9), 3, 3)
foreach(i = 1:nrow(m), .combine = rbind) %dopar%
  (m[i, ] / mean(m[i, ]))
#>               [,1]      [,2]       [,3]
#> result.1  1.137137  2.448800 -0.5859375
#> result.2 -8.252064 -6.443730 17.6957942
#> result.3 -2.179046  1.787817  3.3912295
# simple parallel matrix multiply
a <- matrix(1:16, 4, 4)
b <- t(a)
foreach(b = iter(b, by='col'), .combine = cbind) %dopar%
  (a %*% b)
#>      [,1] [,2] [,3] [,4]
#> [1,]  276  304  332  360
#> [2,]  304  336  368  400
#> [3,]  332  368  404  440
#> [4,]  360  400  440  480
```
