---
title: "mirai - Torch Integration"
vignette: >
  %\VignetteIndexEntry{mirai - Torch Integration}
  %\VignetteEngine{litedown::vignette}
  %\VignetteEncoding{UTF-8}
---


### Torch Integration

Custom serialization functions may be registered to handle external pointer type reference objects.

This allows tensors from the [`torch`](https://torch.mlverse.org/) package to be used seamlessly in 'mirai' computations.

#### Setup Steps

1. Create the serialization configuration, specifying 'class' as 'torch_tensor' and 'vec' as TRUE.
1. Set up daemons, supplying the configuration to the 'serial' argument.
1. (Optional) Use `everywhere()` to make the `torch` package available on all daemons for convenience.


``` r
library(mirai)
library(torch)

cfg <- serial_config(
  class = "torch_tensor",
  sfunc = torch::torch_serialize,
  ufunc = torch::torch_load,
  vec = TRUE
)

daemons(1, serial = cfg)
#> [1] 1

everywhere(library(torch))
```
#### Example Usage

The below example creates a convolutional neural network using `torch::nn_module()`.

A set of model parameters is also specified.

The model specification and parameters are then passed to and initialized within a 'mirai'.


``` r
model <- nn_module(
  initialize = function(in_size, out_size) {
    self$conv1 <- nn_conv2d(in_size, out_size, 5)
    self$conv2 <- nn_conv2d(in_size, out_size, 5)
  },
  forward = function(x) {
    x <- self$conv1(x)
    x <- nnf_relu(x)
    x <- self$conv2(x)
    x <- nnf_relu(x)
    x
  }
)

params <- list(in_size = 1, out_size = 20)

m <- mirai(do.call(model, params), model = model, params = params)

m[]
#> An `nn_module` containing 1,040 parameters.
#> 
#> ── Modules ───────────────────────────────────────────────────────────────────────────────────────────────────────
#> • conv1: <nn_conv2d> #520 parameters
#> • conv2: <nn_conv2d> #520 parameters
```
The returned model is an object containing many tensor elements.

``` r
m$data$parameters$conv1.weight
#> torch_tensor
#> (1,1,.,.) = 
#>   0.0654 -0.1358 -0.1021 -0.1275  0.0629
#>  -0.1940  0.1276  0.0844  0.1156 -0.0534
#>   0.0052 -0.1436  0.1437 -0.0333  0.1231
#>  -0.0335 -0.1973 -0.0195  0.0169  0.0695
#>  -0.0103  0.1873  0.0336 -0.0433 -0.1199
#> 
#> (2,1,.,.) = 
#>   0.1589  0.1709  0.0429 -0.1742  0.1243
#>  -0.0342 -0.0472 -0.0577  0.0704  0.1244
#>  -0.0562  0.1187  0.0600  0.0833 -0.0774
#>  -0.0711 -0.0083  0.0781 -0.1742 -0.0315
#>  -0.1749  0.1339  0.0663  0.0882 -0.0210
#> 
#> (3,1,.,.) = 
#>   0.1821 -0.1932  0.1553  0.0678 -0.1192
#>  -0.0923 -0.0381 -0.0822  0.0870  0.1834
#>  -0.0088 -0.0990  0.0062 -0.0105  0.0109
#>  -0.1154  0.0633 -0.0290 -0.1989 -0.0275
#>   0.1518 -0.1719 -0.1890  0.1123 -0.1981
#> 
#> (4,1,.,.) = 
#>  -0.0238 -0.0420 -0.0309 -0.1841 -0.1106
#>   0.0380 -0.1420 -0.0526 -0.1388 -0.0601
#>  -0.0083 -0.1878  0.0763  0.0734  0.0937
#>   0.0159  0.0897 -0.1605  0.1789 -0.1066
#>  -0.1406  0.0467  0.1624 -0.1767 -0.0557
#> 
#> (5,1,.,.) = 
#>   0.0337  0.1287 -0.1257 -0.0342  0.0709
#> ... [the output was truncated (use n=-1 to disable)]
#> [ CPUFloatType{20,1,5,5} ][ requires_grad = TRUE ]
```
It is usual for model parameters to then be passed to an optimiser.

This can also be initialized within a 'mirai' process.

``` r
optim <- mirai(optim_rmsprop(params = params), params = m$data$parameters)

optim[]
#> <optim_rmsprop>
#>   Inherits from: <torch_optimizer>
#>   Public:
#>     add_param_group: function (param_group) 
#>     clone: function (deep = FALSE) 
#>     defaults: list
#>     initialize: function (params, lr = 0.01, alpha = 0.99, eps = 1e-08, weight_decay = 0, 
#>     load_state_dict: function (state_dict, ..., .refer_to_state_dict = FALSE) 
#>     param_groups: list
#>     state: State, R6
#>     state_dict: function () 
#>     step: function (closure = NULL) 
#>     zero_grad: function (set_to_none = FALSE) 
#>   Private:
#>     deep_clone: function (name, value) 
#>     step_helper: function (closure, loop_fun)

daemons(0)
#> [1] 0
```
Above, tensors and complex objects containing tensors were passed seamlessly between host and daemon processes, in the same way as any other R object.

The custom serialization in `mirai` leverages R's own native 'refhook' mechanism to allow such completely transparent usage. Designed to be fast and efficient, data copies are minimised and the 'official' serialization methods from the `torch` package are used directly.
